name: api_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  cloud_functions: ^6.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  google_sign_in: ^7.1.1
  google_sign_in_platform_interface: ^3.0.0
  google_sign_in_ios: ^6.1.0
  google_sign_in_android: ^7.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
