name: api_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
