name: api_client
description: CI-Server API Client for CI-Connect application.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  sqflite: ^2.3.3+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  sqflite_common_ffi: ^2.3.3
