name: app_core
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  bloc: ^9.0.0
  collection: ^1.19.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  formz: ^0.8.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  rxdart: ^0.28.0
  slugify: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
