name: app_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  animations: ^2.0.11
  app_core:
    path: ../app_core
  cached_network_image: ^3.4.1
  country_flags: ^3.2.0
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_cache_manager: ^3.4.1
  go_router: ^16.1.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  intl: ^0.20.2
  provider: ^6.1.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
